Soumya Khanna

PRN: 25070123111

Title: Tools for EDA-  Study of NumPy Library

In [ ]:
#Declaration of numpy
import numpy as np

a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

#dimension of array
print(a.ndim)
print(b.ndim)

#shape

print(a.shape)
b.shape

#type

print(a.dtype)
print(b.dtype)

#size

print(a.size)
print(b.size)

#in built function using numpy
print(np.zeros((2,3)))

print(np.ones((3,3)))

print(np.eye((3)))

print(np.arange(1,10,2))

print(np.linspace(0,1,4))

print(b * 2)
print(a + 5)

print(np.mean(a))

print(np.median(a))

np.max(a)



[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]
1
2
(7,)
int64
int64
7
6
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[0.         0.33333333 0.66666667 1.        ]
[[ 2  4  6]
 [ 8 10 12]]
[  6  15  25  35  45  55 505]
93.0
30.0


np.int64(500)

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:")
print(matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
determinant = np.linalg.det(matrix)
transpose = matrix.T

print("Determinant of the matrix:", determinant)
print("Transpose of the matrix:")
print(transpose)

Determinant of the matrix: 0.0
Transpose of the matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [1]:
import numpy as np

# Define two matrices
matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

result_dot = np.dot(matrix1, matrix2)

result_at = matrix1 @ matrix2

print("\nResult of matrix multiplication (using np.dot()):")
print(result_dot)

print("\nResult of matrix multiplication (using @ operator):")
print(result_at)

Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Result of matrix multiplication (using np.dot()):
[[19 22]
 [43 50]]

Result of matrix multiplication (using @ operator):
[[19 22]
 [43 50]]
